#!/bin/sh -e
#
# phoronix
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
nohup phoronix-test-suite phoromatic.connect 192.168.2.2:1234/PLSDKS > /var/log/phoronix/phoronix.log &
exit 0
